/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEDoodleJumpInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getJumpHistory"
      | "getLastJump"
      | "getTotalJumps"
      | "protocolId"
      | "submitJump"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getJumpHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastJump",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalJumps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitJump",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getJumpHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastJump",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalJumps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitJump", data: BytesLike): Result;
}

export interface FHEDoodleJump extends BaseContract {
  connect(runner?: ContractRunner | null): FHEDoodleJump;
  waitForDeployment(): Promise<this>;

  interface: FHEDoodleJumpInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getJumpHistory: TypedContractMethod<
    [player: AddressLike],
    [string[]],
    "view"
  >;

  getLastJump: TypedContractMethod<[], [string], "view">;

  getTotalJumps: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitJump: TypedContractMethod<
    [encryptedJump: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getJumpHistory"
  ): TypedContractMethod<[player: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getLastJump"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalJumps"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitJump"
  ): TypedContractMethod<
    [encryptedJump: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
